"use client";

import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Download, Loader2, X } from "lucide-react";
import { motion } from "framer-motion";
import Image from "next/image";

interface ImageModalProps {
  isOpen: boolean;
  onClose: () => void;
  imageUrl: string | null;
  title: string;
  isLoading: boolean;
}

export default function ImageModal({ isOpen, onClose, imageUrl, title, isLoading }: ImageModalProps) {
  const [imageError, setImageError] = useState(false);

  const handleDownload = async () => {
    if (!imageUrl) return;

    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${title.replace(/\s+/g, '_')}.png`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (error) {
      console.error('Failed to download image:', error);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center justify-between">
            <span>{title}</span>
            <Button variant="ghost" size="sm" onClick={onClose}>
              <X className="w-4 h-4" />
            </Button>
          </DialogTitle>
        </DialogHeader>

        <div className="relative aspect-square w-full bg-gray-100 dark:bg-gray-800 rounded-lg overflow-hidden">
          {isLoading && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="absolute inset-0 flex flex-col items-center justify-center"
            >
              <Loader2 className="w-12 h-12 animate-spin text-purple-600 mb-4" />
              <p className="text-sm text-gray-600 dark:text-gray-400">
                Generating AI image...
              </p>
            </motion.div>
          )}

          {!isLoading && imageUrl && !imageError && (
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.3 }}
              className="relative w-full h-full"
            >
              <Image
                src={imageUrl}
                alt={title}
                fill
                className="object-cover"
                onError={() => setImageError(true)}
                unoptimized 
              />
            </motion.div>
          )}

          {!isLoading && imageError && (
            <div className="absolute inset-0 flex flex-col items-center justify-center p-8 text-center">
              <div className="text-4xl mb-4">🖼️</div>
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">
                Failed to load image
              </p>
              <p className="text-xs text-gray-500">
                The image service might be temporarily unavailable
              </p>
            </div>
          )}
        </div>

        {!isLoading && imageUrl && !imageError && (
          <div className="flex gap-2 justify-end">
            <Button
              onClick={handleDownload}
              className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700"
            >
              <Download className="w-4 h-4 mr-2" />
              Download
            </Button>
          </div>
        )}

        <p className="text-xs text-gray-500 text-center">
          Images generated by AI • Free via Pollinations.ai
        </p>
      </DialogContent>
    </Dialog>
  );
}
