"use client";

import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import { Button } from "@/components/ui/button";
import { Dumbbell, Brain, TrendingUp, Sparkles } from "lucide-react";
import { ThemeToggle } from "@/components/ThemeToggle";
import FitnessVideoBackground from "./FitnessVideoBackground";

interface LandingPageProps {
  onGetStarted: () => void;
  onViewSavedPlans: () => void;
}

export default function LandingPage({ onGetStarted, onViewSavedPlans }: LandingPageProps) {
  const featuresRef = useRef(null);
  const howItWorksRef = useRef(null);
  const ctaRef = useRef(null);
    const cardRefs = useRef<(HTMLDivElement | null)[]>([]);
  
  const featuresInView = useInView(featuresRef, { once: true, amount: 0.2 });
  const howItWorksInView = useInView(howItWorksRef, { once: true, amount: 0.3 });
  const ctaInView = useInView(ctaRef, { once: true, amount: 0.5 });

  const fadeInUp = {
    initial: { opacity: 0, y: 60 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.6 }
  };

  const staggerContainer = {
    animate: {
      transition: {
        staggerChildren: 0.1
      }
    }
  };

  const cardVariants = {
    hidden: { 
      opacity: 0, 
      y: 100, 
      scale: 0.8 
    },
    visible: {
      opacity: 1,
      y: 0,
      scale: 1
    }
  };

  const features = [
    {
      icon: Brain,
      title: "AI-Powered Plans",
      description: "Get personalized workout and diet plans generated by advanced AI"
    },
    {
      icon: Dumbbell,
      title: "Custom Workouts",
      description: "Tailored exercises based on your fitness level and goals"
    },
    {
      icon: TrendingUp,
      title: "Track Progress",
      description: "Monitor your fitness journey with detailed insights"
    },
    {
      icon: Sparkles,
      title: "Smart Features",
      description: "Voice guidance, AI images, and PDF export for your plans"
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-white to-blue-50 dark:from-black dark:via-gray-950 dark:to-black relative overflow-hidden">
      {/* Theme Toggle - Fixed Position */}
      <div className="fixed top-4 right-4 z-50">
        <ThemeToggle />
      </div>
      
      {/* 3D Background */}
      <FitnessVideoBackground />
      
      {/* Background 3D Fitness Animation */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        {/* Animated gradient orbs */}
        <motion.div
          animate={{
            scale: [1, 1.2, 1],
            rotate: [0, 90, 0],
            opacity: [0.3, 0.5, 0.3]
          }}
          transition={{
            duration: 20,
            repeat: Infinity,
            ease: "linear"
          }}
          className="absolute -top-40 -left-40 w-96 h-96 bg-purple-500/20 dark:bg-purple-500/10 rounded-full blur-3xl"
        />
        <motion.div
          animate={{
            scale: [1.2, 1, 1.2],
            rotate: [90, 0, 90],
            opacity: [0.3, 0.5, 0.3]
          }}
          transition={{
            duration: 25,
            repeat: Infinity,
            ease: "linear"
          }}
          className="absolute -bottom-40 -right-40 w-96 h-96 bg-blue-500/20 dark:bg-blue-500/10 rounded-full blur-3xl"
        />
        <motion.div
          animate={{
            y: [0, -50, 0],
            x: [0, 50, 0],
            scale: [1, 1.1, 1],
            opacity: [0.2, 0.4, 0.2]
          }}
          transition={{
            duration: 15,
            repeat: Infinity,
            ease: "easeInOut"
          }}
          className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-gradient-to-r from-purple-400/10 to-blue-400/10 dark:from-purple-600/5 dark:to-blue-600/5 rounded-full blur-3xl"
        />
        
        {/* Floating dumbbell icons */}
        {[...Array(6)].map((_, i) => (
          <motion.div
            key={i}
            animate={{
              y: [0, -100, 0],
              x: [0, Math.random() * 100 - 50, 0],
              rotate: [0, 360],
              opacity: [0.1, 0.3, 0.1]
            }}
            transition={{
              duration: 10 + i * 2,
              repeat: Infinity,
              delay: i * 1.5,
              ease: "easeInOut"
            }}
            className="absolute"
            style={{
              left: `${10 + i * 15}%`,
              top: `${20 + (i % 3) * 30}%`
            }}
          >
            <Dumbbell className="w-12 h-12 text-purple-300/20 dark:text-purple-500/10" />
          </motion.div>
        ))}
      </div>

      <div className="container mx-auto px-4 relative z-10">
        {/* Hero Section */}
        <motion.div
          initial="initial"
          animate="animate"
          variants={staggerContainer}
          className="text-center max-w-4xl mx-auto min-h-screen flex flex-col justify-center"
        >
          <motion.div
            variants={fadeInUp}
            className="inline-flex items-center justify-center gap-2 bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 px-4 py-2 rounded-full text-sm font-medium mb-8 mx-auto"
          >
            <Sparkles className="w-4 h-4" />
            AI-Powered Fitness Coach
          </motion.div>

          <motion.h1
            variants={fadeInUp}
            className="text-5xl md:text-7xl font-bold mb-6 bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent"
          >
            Transform Your Body
            <br />
            With AI Guidance
          </motion.h1>

          <motion.p
            variants={fadeInUp}
            className="text-xl text-gray-600 dark:text-gray-300 mb-8 max-w-2xl mx-auto"
          >
            Get personalized workout routines and meal plans tailored to your goals, 
            fitness level, and preferences. Powered by cutting-edge AI technology.
          </motion.p>

          <motion.div variants={fadeInUp} className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Button
              size="lg"
              onClick={onGetStarted}
              className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white px-8 py-6 text-lg rounded-full shadow-lg hover:shadow-xl transition-all"
            >
              Get Started Free
              <motion.span
                animate={{ x: [0, 5, 0] }}
                transition={{ repeat: Infinity, duration: 1.5 }}
                className="ml-2"
              >
                →
              </motion.span>
            </Button>
            <Button
              size="lg"
              onClick={onViewSavedPlans}
              variant="outline"
              className="px-8 py-6 text-lg rounded-full border-2 border-purple-600 dark:border-purple-400 text-purple-600 dark:text-purple-400 hover:bg-purple-50 dark:hover:bg-purple-900/20"
            >
              📋 View Saved Plans
            </Button>
          </motion.div>
        </motion.div>

        {/* Features Grid */}
        <div
          ref={featuresRef}
          className="grid md:grid-cols-2 lg:grid-cols-4 gap-8 py-20 px-4"
        >
          {features.map((feature, index) => {
            const FeatureCard = () => {
              const cardRef = useRef(null);
              const isInView = useInView(cardRef, { once: true, amount: 0.3 });
              
              return (
                <motion.div
                  ref={cardRef}
                  initial="hidden"
                  animate={isInView ? "visible" : "hidden"}
                  variants={cardVariants}
                  transition={{ 
                    delay: 0.1,
                    duration: 0.6,
                    ease: "easeOut"
                  }}
                  whileHover={{ scale: 1.05, y: -10 }}
                  className="bg-white/90 dark:bg-gray-900/50 backdrop-blur-sm p-6 rounded-2xl shadow-lg hover:shadow-xl transition-shadow border border-purple-100 dark:border-gray-700"
                >
                  <div className="bg-gradient-to-br from-purple-500 to-blue-500 w-12 h-12 rounded-lg flex items-center justify-center mb-4">
                    <feature.icon className="w-6 h-6 text-white" />
                  </div>
                  <h3 className="text-xl font-semibold mb-2 text-gray-800 dark:text-white">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600 dark:text-gray-300">
                    {feature.description}
                  </p>
                </motion.div>
              );
            };
            
            return <FeatureCard key={index} />;
          })}
        </div>

        {/* How It Works */}
        <motion.div
          ref={howItWorksRef}
          className="text-center max-w-3xl mx-auto py-20 px-4"
        >
          <motion.h2
            initial={{ opacity: 0, y: 30 }}
            animate={howItWorksInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
            transition={{ duration: 0.6 }}
            className="text-3xl md:text-4xl font-bold mb-6 text-gray-800 dark:text-white"
          >
            How It Works
          </motion.h2>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { step: "1", title: "Share Your Details", desc: "Tell us about your fitness goals and preferences" },
              { step: "2", title: "AI Creates Your Plan", desc: "Our AI generates a personalized workout and diet plan" },
              { step: "3", title: "Start Your Journey", desc: "Follow your plan and track your progress" }
            ].map((item, index) => {
              const StepCard = () => {
                const stepRef = useRef(null);
                const isInView = useInView(stepRef, { once: true, amount: 0.5 });
                
                return (
                  <motion.div
                    ref={stepRef}
                    initial={{ opacity: 0, y: 80, scale: 0.8 }}
                    animate={isInView ? { opacity: 1, y: 0, scale: 1 } : { opacity: 0, y: 80, scale: 0.8 }}
                    transition={{ delay: 0.1, duration: 0.6, ease: "easeOut" }}
                    className="relative"
                  >
                    <div className="bg-gradient-to-br from-purple-600 to-blue-600 text-white w-12 h-12 rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                      {item.step}
                    </div>
                    <h3 className="font-semibold text-lg mb-2 text-gray-800 dark:text-white">
                      {item.title}
                    </h3>
                    <p className="text-gray-600 dark:text-gray-300">
                      {item.desc}
                    </p>
                  </motion.div>
                );
              };
              
              return <StepCard key={index} />;
            })}
          </div>
        </motion.div>

        {/* CTA Section */}
        <motion.div
          ref={ctaRef}
          initial={{ opacity: 0, scale: 0.9, y: 50 }}
          animate={ctaInView ? { opacity: 1, scale: 1, y: 0 } : { opacity: 0, scale: 0.9, y: 50 }}
          transition={{ duration: 0.7 }}
          className="my-20 mx-4 text-center bg-gradient-to-r from-purple-600 to-blue-600 rounded-3xl p-12 text-white relative overflow-hidden"
        >
          {/* Animated background pattern */}
          <motion.div
            animate={{
              rotate: [0, 360],
              scale: [1, 1.1, 1]
            }}
            transition={{
              duration: 20,
              repeat: Infinity,
              ease: "linear"
            }}
            className="absolute inset-0 opacity-10"
          >
            <div className="absolute inset-0" style={{
              backgroundImage: `radial-gradient(circle, white 1px, transparent 1px)`,
              backgroundSize: '30px 30px'
            }} />
          </motion.div>
          <div className="relative z-10">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Ready to Transform Your Life?
            </h2>
            <p className="text-xl mb-8 opacity-90">
              Join thousands who have achieved their fitness goals with AI guidance
            </p>
            <Button
              size="lg"
              onClick={onGetStarted}
              className="bg-white text-purple-600 hover:bg-gray-100 px-8 py-6 text-lg rounded-full shadow-lg"
            >
              Start Your Journey Now
            </Button>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
